"""add file_path to Task

Revision ID: 140cdff31ab2
Revises: c1fd03eb9de4
Create Date: 2025-08-26 19:07:29.619106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '140cdff31ab2'
down_revision = 'c1fd03eb9de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
